name: Run Cypress Test

on: [push]

jobs:
  cypress-runner:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node
        uses: actions/checkout@v4

      - name: Run Cypress Scripts
        uses: cypress-io/github-action@v6

      - name: Upload Test Report
        uses: actions/upload-artifact@v3
        with:
          name: cucumber-report
          path: /cypress/reports/html/e2e-repot.html

      - name: Upload to Browserstack
        uses: "browserstack/github-actions/setup-env@master"
        with:
          username: ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

      - run: npm install
      - run: npx browserstack-cypress run
